architect:
  - emilianodellacasa
decrypt:
  credentials.json: "repo/credentials/credentials.json.asc"
  staging.id_rsa: "repo/credentials/staging.id_rsa.asc"
  staging.id_rsa.pub: "repo/credentials/staging.id_rsa.pub.asc"
install: |-
  sudo add-apt-repository -y ppa:jonathonf/python-3.6
  sudo apt-get update
  sudo apt-get -y install python3.6 python3.6-dev python3.6-venv
  python3.6 -m venv venv
  . venv/bin/activate
  pip install -r requirements.txt
  sudo gem install pdd
  sudo apt-get install sshpass
  chmod +x scripts/install/install_db.sh
  ./scripts/install/install_db.sh
  chmod +x scripts/install/installRedis.sh
  ./scripts/install/installRedis.sh
merge:
  script: |-
    python checkstyle.py
    python check_pylint.py
    pytest -vv
    # @todo #514:30m React Frontend tests should be also executed in CI. The command is "cd frontend && npm test". Coverage should be also reported, maybe this another puzzle.
    pdd -f /dev/null -v
deploy:
  script: |-
    chmod +x ./deploy.sh
    ./deploy.sh
release:
  script: |-
    echo "Release not supported"
    exit -1
