architect:
  - emilianodellacasa
install: |-
  sudo apt-get -y install python3 python3-dev python3-venv
  python3 -m venv venv
  . venv/bin/activate
  pip install -r requirements.txt
  sudo gem install pdd
  sudo /etc/init.d/postgresql start
  sudo -u postgres psql -c "CREATE USER timeless_user WITH 
    SUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    LOGIN
    ENCRYPTED PASSWORD 'timeless_pwd';"
  sudo -u postgres psql -c "CREATE DATABASE timelessdb_dev;"
  sudo -u postgres psql -c "CREATE DATABASE timelessdb_test;"
merge:
  script: |-
    chmod +x ./checkstyle.sh
    ./checkstyle.sh
    python check_pylint.py
    pytest -vv
    pdd -f /dev/null -v
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
release:
  script: |-
    echo "There is nothing to release"
    exit -1

