"""empty message

Revision ID: 0d17ec999973
Revises: 79f280c6c1f4
Create Date: 2019-01-27 17:17:34.375836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d17ec999973'
down_revision = '79f280c6c1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('code', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('name', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['code'])
    op.create_unique_constraint(None, 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'updated_on')
    op.drop_column('companies', 'name')
    op.drop_column('companies', 'created_on')
    op.drop_column('companies', 'code')
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
