"""empty message

Revision ID: 8e4ed4542586
Revises: 6069798906d9
Create Date: 2019-01-27 16:06:34.295510

"""

# revision identifiers, used by Alembic.
revision = '8e4ed4542586'
down_revision = '6069798906d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
