"""empty message

Revision ID: fb887393e975
Revises: 7f38c5d3030d
Create Date: 2019-02-10 18:59:48.800057+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb887393e975'
down_revision = '7f38c5d3030d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('synchronized_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('num_of_persons', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('unconfirmed', 'confirmed', 'started', 'finished', 'canceled', 'late', 'not_contacting', name='reservationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tables', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('synchronized_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'synchronized_on')
    op.drop_column('tables', 'poster_id')
    op.drop_table('table_reservations')
    op.drop_table('reservations')
    op.drop_table('customers')
    # ### end Alembic commands ###
