"""empty message

Revision ID: 4207a669d969
Revises: 9eee25222512
Create Date: 2019-01-28 23:29:28.255031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4207a669d969'
down_revision = '1029025e393e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('default_duration', sa.SmallInteger(), nullable=True),
    sa.Column('default_deposit', sa.SmallInteger(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('threshold_sms_time', sa.SmallInteger(), nullable=True),
    sa.Column('greeting_by_time', sa.JSON(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_settings')
    # ### end Alembic commands ###
