"""empty message

Revision ID: 65535c7283b5
Revises: fb887393e975
Create Date: 2019-02-26 05:45:08.668445+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65535c7283b5'
down_revision = 'fb887393e975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees',
                  sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employees_roles',
                          'employees', 'roles',
                          ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_roles', 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    # ### end Alembic commands ###
