"""empty message

Revision ID: 4150cff9d24d
Revises: 9eee25222512
Create Date: 2019-01-29 07:25:32.697988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4150cff9d24d'
down_revision = '9eee25222512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'poster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
