"""empty message

Revision ID: 4d7589fae495
Revises: be62103a5fd6
Create Date: 2019-01-24 10:28:04.239895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7589fae495'
down_revision = 'be62103a5fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('code', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'companies', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'updated_on')
    op.drop_column('companies', 'created_on')
    op.drop_column('companies', 'code')
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
