"""empty message

Revision ID: 503a67df3f7f
Revises: 
Create Date: 2019-01-21 16:20:49.552051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503a67df3f7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
