"""empty message

Revision ID: 9eee25222512
Revises: 0d17ec999973
Create Date: 2019-01-27 17:22:04.604430

"""

# revision identifiers, used by Alembic.
revision = '9eee25222512'
down_revision = '79f280c6c1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
